###
GET http://localhost:3000/

###
GET http://localhost:3000/shorturls

###
GET http://localhost:3000/shortener

###
GET http://localhost:3000/shortener/507a129b-58d9-49a6-beef-6da8858a16d6

###
POST http://localhost:3000/url
Content-Type: application/json

{
  "shortURL": "http://localhost:3000/sl5mfaqs"
}

###
POST http://localhost:3000/shortener/date
Content-Type: application/json

{
  "date": "2022-09-05T03:00:00.000Z"
}

###
POST http://localhost:3000/shortener
Content-Type: application/json

{
  "url": "https://web.whatsapp.com/"
}
