###
GET http://localhost:3000/

###
GET http://localhost:3000/shorturls

###
GET http://localhost:3000/shortener

###
GET http://localhost:3000/shortener/5ffe8b7d-d494-49e4-ad47-5acd031701d9

###
POST http://localhost:3000/url
Content-Type: application/json

{
  "shortURL": "http://localhost:3000/rmnbyyxf"
}

###
POST http://localhost:3000/shortener/date
Content-Type: application/json

{
  "date": "2022-09-01T03:00:00.000Z"
}

###
POST http://localhost:3000/shortener
Content-Type: application/json

{
  "url": "https://web.whatsapp.com/"
}
